harnessApiVersion: '1.0'
type: PIPELINE
description: Helm Basic Deployment Pipeline Dev to Prod
pipelineStages:
- type: ENV_STATE
  disable: false
  name: Deploy to Dev
  parallel: false
  stageName: STAGE 1
  workflowName: helm-basic-workflow
  workflowVariables:
  - entityType: INFRASTRUCTURE_MAPPING
    name: ServiceInfra_HELM
    value: dev-esnode-cs
  - entityType: ENVIRONMENT
    name: Environment
    value: dev
  - entityType: SERVICE
    name: Service
    value: metric-server
- type: APPROVAL
  disable: false
  name: Approval 1
  parallel: false
  properties:
    userGroups:
    - OwqgwBkJSt2Vqlv-_TNfUA
    timeoutMillis: 604800000
    approvalStateType: USER_GROUP
  stageName: STAGE 2
- type: ENV_STATE
  disable: false
  name: Deploy to Production
  parallel: false
  stageName: STAGE 3
  workflowName: helm-basic-workflow
  workflowVariables:
  - entityType: INFRASTRUCTURE_MAPPING
    name: ServiceInfra_HELM
    value: Kubernetes Cluster_ CS Cluster_DIRECT_Kubernetes_prod
  - entityType: ENVIRONMENT
    name: Environment
    value: prod
  - entityType: SERVICE
    name: Service
    value: metric-server
