harnessApiVersion: '1.0'
type: BLUE_GREEN
description: Basic Kubernetes V2 Deployment
envName: dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - OwqgwBkJSt2Vqlv-_TNfUA
phases:
- type: KUBERNETES
  computeProviderName: CS Cluster
  daemonSet: false
  infraMappingName: kubewatch-esnode-cs-cluster
  name: Blue/Green
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_BLUE_GREEN_DEPLOY
      name: Stage Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Route Update
    steps:
    - type: KUBERNETES_SWAP_SERVICE_SELECTORS
      name: Swap Primary with Stage
      properties:
        service1: ${k8s.primaryServiceName}
        service2: ${k8s.stageServiceName}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: k8sv2
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: CS Cluster
  daemonSet: false
  infraMappingName: kubewatch-esnode-cs-cluster
  name: Rollback Blue/Green
  phaseNameForRollback: Blue/Green
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Route Update
    phaseStepNameForRollback: Route Update
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: k8sv2
  statefulSet: false
templatized: false
