harnessApiVersion: '1.0'
type: ROLLING
description: Rolling deployment with Kubewatch in K8V2 setup
envName: rolling-dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - OwqgwBkJSt2Vqlv-_TNfUA
phases:
- type: KUBERNETES
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: rolling-dev-blackbelt-k8s
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    - type: SHELL_SCRIPT
      name: Shell Script
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: echo "${serviceVariable.NOTASECRET}"
        scriptType: BASH
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: ''
        templateVariables: ''
        timeoutMillis: 60000
    - type: SHELL_SCRIPT
      name: Shell Script_2
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: echo "{{.Values.env.name}}"
        scriptType: BASH
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: ''
        templateVariables: ''
        timeoutMillis: 60000
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: kubewatch
  statefulSet: false
  templateExpressions:
  - expression: ${Service}
    fieldName: serviceId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
      value: ${ServiceInfra_Kubernetes}
    - name: entityType
      value: SERVICE
  - expression: ${ServiceInfra_Kubernetes}
    fieldName: infraMappingId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_MAPPING
rollbackPhases:
- type: KUBERNETES
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: rolling-dev-blackbelt-k8s
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: kubewatch
  statefulSet: false
  templateExpressions:
  - expression: ${Service}
    fieldName: serviceId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
      value: ${ServiceInfra_Kubernetes}
    - name: entityType
      value: SERVICE
  - expression: ${ServiceInfra_Kubernetes}
    fieldName: infraMappingId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_MAPPING
templateExpressions:
- expression: ${Service}
  fieldName: serviceId
  metadata:
  - name: artifactType
    value: DOCKER
  - name: relatedField
    value: ${ServiceInfra_Kubernetes}
  - name: entityType
    value: SERVICE
- expression: ${ServiceInfra_Kubernetes}
  fieldName: infraMappingId
  metadata:
  - name: artifactType
    value: DOCKER
  - name: relatedField
  - name: entityType
    value: INFRASTRUCTURE_MAPPING
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Service entity in Rollback Rolling
  fixed: false
  mandatory: true
  name: Service
- type: ENTITY
  description: Variable for Service Infra-structure entity in Rollback Rolling
  fixed: false
  mandatory: true
  name: ServiceInfra_Kubernetes
