harnessApiVersion: '1.0'
type: BLUE_GREEN
description: Blue Green MyChart Deployment
envName: dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - OwqgwBkJSt2Vqlv-_TNfUA
phases:
- type: KUBERNETES
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: blackbelt_dev_mychart
  name: Blue/Green
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_BLUE_GREEN_DEPLOY
      name: Stage Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: SHELL_SCRIPT
      name: Get Services in a Namespace
      properties:
        commandPath: null
        connectionAttributes: null
        connectionType: SSH
        executeOnDelegate: true
        host: null
        publishAsVar: false
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: ''
        templateUuid: lFtpqFDfSY2EE7kdKSCB6Q
        templateVariables:
        - name: kns
          type: TEXT
          value: bgdemo
          description: dev namespace by default
        templateVersion: latest
        timeoutMillis: 600000
        variables:
        - name: kns
          type: TEXT
          value: bgdemo
          description: dev namespace by default
      templateUri: Harness-BB/Kubernetes Commands/Get Services in a Namespace:latest
      templateVariables:
      - name: kns
        value: bgdemo
    - type: SHELL_SCRIPT
      name: Shell Script_2
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: exit 0
        scriptType: BASH
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: ''
        templateVariables: ''
        timeoutMillis: 60000
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Route Update
    steps:
    - type: KUBERNETES_SWAP_SERVICE_SELECTORS
      name: Swap Primary with Stage
      properties:
        service1: ${k8s.primaryServiceName}
        service2: ${k8s.stageServiceName}
        templateUuid: null
        templateVariables: null
        templateVersion: null
    - type: SHELL_SCRIPT
      name: Get Services in a Namespace
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        publishAsVar: false
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: ''
        templateUuid: lFtpqFDfSY2EE7kdKSCB6Q
        templateVariables:
        - name: kns
          description: dev namespace by default
          mandatory: false
          value: bgdemo
          fixed: false
          metadata: null
          type: TEXT
        templateVersion: latest
        timeoutMillis: 600000
        variables:
        - name: kns
          type: TEXT
          value: bgdemo
          description: dev namespace by default
      templateUri: Harness-BB/Kubernetes Commands/Get Services in a Namespace:latest
      templateVariables:
      - name: kns
        value: bgdemo
    - type: HTTP
      name: Health Check Primary
      properties:
        assertion: ''
        body: ''
        executeWithPreviousSteps: false
        header: ''
        method: GET
        publishAsVar: false
        responseProcessingExpressions: ''
        sweepingOutputName: null
        sweepingOutputScope: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 10000
        url: http://34.82.100.1
    - type: HTTP
      name: Health Check Stage
      properties:
        assertion: ''
        body: ''
        executeWithPreviousSteps: true
        header: ''
        method: GET
        publishAsVar: false
        responseProcessingExpressions: ''
        sweepingOutputName: null
        sweepingOutputScope: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeoutMillis: 10000
        url: http://35.233.136.206
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: EMAIL
      name: Email
      properties:
        body: "${app.name} was successfully deployed in ${infra.kubernetes.namespace}.\
          \ \n\n${workflow.name} was run and the last successful run was ${workflow.lastGoodDeploymentDisplayName}\n\
          \nThe Deployment was triggered by: ${deploymentTriggeredBy}\n\nThe URL to\
          \ the deployment: ${deploymentUrl}"
        subject: MyChart BlueGreen Deployment Summary
        toAddress: rohan@harness.io
    stepsInParallel: false
  provisionNodes: false
  serviceName: MyChart
  statefulSet: false
templatized: false
