harnessApiVersion: '1.0'
type: BLUE_GREEN
description: Blue Green MyChart Deployment
envName: dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - OwqgwBkJSt2Vqlv-_TNfUA
phases:
- type: KUBERNETES
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: blackbelt_dev_mychart
  name: Blue/Green
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_BLUE_GREEN_DEPLOY
      name: Stage Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: SHELL_SCRIPT
      name: Get Services in a Namespace
      properties:
        executeOnDelegate: true
        timeoutMillis: 600000
      templateUri: Harness-BB/Kubernetes Commands/Get Services in a Namespace:latest
      templateVariables:
      - name: kns
        value: dev
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Route Update
    steps:
    - type: KUBERNETES_SWAP_SERVICE_SELECTORS
      name: Swap Primary with Stage
      properties:
        service1: ${k8s.primaryServiceName}
        service2: ${k8s.stageServiceName}
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: MyChart
  statefulSet: false
templatized: false
