harnessApiVersion: '1.0'
type: BASIC
envName: rolling-dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - OwqgwBkJSt2Vqlv-_TNfUA
phases:
- type: HELM
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: blackbet_k8s_rollingdev
  name: Phase 1
  phaseSteps:
  - type: HELM_DEPLOY
    name: Deploy Containers
    steps:
    - type: HELM_DEPLOY
      name: Helm Deploy
      properties:
        connectionType: branch
        gitFileConfig:
          connectorId: YRgKxN10Q_-KXBcdJt-nYQ
          commitId: null
          branch: develop
          filePath: mychart/values.yaml
          useBranch: true
        helmReleaseNamePrefix: HelmHook
        steadyStateTimeout: 10
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: HelmHook
  statefulSet: false
rollbackPhases:
- type: HELM
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: blackbet_k8s_rollingdev
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: HELM_DEPLOY
    name: Deploy Containers
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    steps:
    - type: HELM_ROLLBACK
      name: Helm Rollback
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: HelmHook
  statefulSet: false
templatized: false
