harnessApiVersion: '1.0'
type: BASIC
description: Helm Basic Workflow Deployment
envName: dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - OwqgwBkJSt2Vqlv-_TNfUA
phases:
- type: HELM
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: dev-metric-server-blackbelt-k8s
  name: Phase 1
  phaseSteps:
  - type: HELM_DEPLOY
    name: Deploy Containers
    steps:
    - type: HELM_DEPLOY
      name: Helm Deploy
      properties:
        gitFileConfig: null
        helmReleaseNamePrefix: ${service.name}-${env.name}-${infra.helm.shortId}
        steadyStateTimeout: 10
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    steps:
    - type: HTTP
      name: HTTP
      properties:
        assertion: ''
        body: ''
        executeWithPreviousSteps: false
        header: ''
        method: GET
        publishAsVar: false
        responseProcessingExpressions: ''
        sweepingOutputName: null
        sweepingOutputScope: null
        templateVariables: ''
        timeoutMillis: 10000
        url: http://10.138.15.219
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: metric-server
  statefulSet: false
rollbackPhases:
- type: HELM
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: dev-metric-server-blackbelt-k8s
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: HELM_DEPLOY
    name: Deploy Containers
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    steps:
    - type: HELM_ROLLBACK
      name: Helm Rollback
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: metric-server
  statefulSet: false
tags:
  demo: helmV1
templatized: false
