harnessApiVersion: '1.0'
type: BASIC
description: Helm Basic Workflow Deployment
envName: dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - OwqgwBkJSt2Vqlv-_TNfUA
phases:
- type: HELM
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: dev-metric-server-blackbelt-k8s
  name: Phase 1
  phaseSteps:
  - type: HELM_DEPLOY
    name: Deploy Containers
    steps:
    - type: HELM_DEPLOY
      name: Helm Deploy
      properties:
        gitFileConfig: null
        helmReleaseNamePrefix: ${service.name}-${env.name}-${infra.helm.shortId}
        steadyStateTimeout: 10
        templateExpressions: null
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    steps:
    - type: SHELL_SCRIPT
      name: Get All in a Specified Namespace
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        publishAsVar: false
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: ''
        templateUuid: qRd4jLvlSxS-bWV0zOmPqA
        templateVariables:
        - name: kns
          type: TEXT
          value: metricserver
          description: Dev namespace by default
        templateVersion: latest
        timeoutMillis: 600000
        variables:
        - name: kns
          type: TEXT
          value: metricserver
          description: Dev namespace by default
      templateUri: Harness-BB/Kubernetes Commands/Get All in a Specified Namespace:latest
      templateVariables:
      - name: kns
        value: metricserver
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    steps:
    - type: SHELL_SCRIPT
      name: Shell Script
      properties:
        commandPath: null
        connectionAttributes: null
        executeOnDelegate: true
        host: null
        outputVars: ''
        publishAsVar: false
        scriptString: "echo \"This chart was deployed in\" ${infra.kubernetes.namespace}\
          \ \n"
        scriptType: BASH
        sshKeyRef: null
        sweepingOutputName: null
        sweepingOutputScope: null
        tags: ''
        templateVariables: ''
        timeoutMillis: 60000
    stepsInParallel: false
  provisionNodes: false
  serviceName: metric-server
  statefulSet: false
rollbackPhases:
- type: HELM
  computeProviderName: blackbelt
  daemonSet: false
  infraMappingName: dev-metric-server-blackbelt-k8s
  name: Rollback Phase 1
  phaseNameForRollback: Phase 1
  phaseSteps:
  - type: HELM_DEPLOY
    name: Deploy Containers
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    steps:
    - type: HELM_ROLLBACK
      name: Helm Rollback
    stepsInParallel: false
  - type: VERIFY_SERVICE
    name: Verify Service
    phaseStepNameForRollback: Deploy Containers
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: WRAP_UP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: metric-server
  statefulSet: false
tags:
  demo: helmV1
templatized: false
